src/main/java/com/boolsazo/bankchall/controller/UserController.java, src/main/java/com/boolsazo/bankchall/domain/User.java, src/main/java/com/boolsazo/bankchall/repository/UserRepository.java, src/main/java/com/boolsazo/bankchall/service/UserService.java, src/main/java/com/boolsazo/bankchall/service/impl/UserServiceImpl.java
- existsByEmail
- registerUser
- findUserIdByEmail
```java
boolean existsByEmail(String email);
void registerUser(String id, String name, String age, String gender, String email,
String birthyear, String profileImage) throws Exception;
void updateFinancialType(int userId, String financialType) throws Exception;
String findFinancialTypeByUserId(int userId) throws Exception;
void deleteByUserId(int userId) throws Exception;
User findOneByUserId(int userId) throws Exception;
int findUserIdByEmail(String email) throws Exception;
```
=> Feat: Create query related to user

frontend/public/index.html, frontend/src/App.js, frontend/src/pages/Hello.js, frontend/src/pages/Main.js, frontend/src/pages/Survey.js, src/main/java/com/boolsazo/bankchall/controller/HelloController.java, src/main/java/com/boolsazo/bankchall/controller/StatusController.java, src/main/java/com/boolsazo/bankchall/controller/UserController.java, src/main/java/com/boolsazo/bankchall/domain/User.java, src/main/java/com/boolsazo/bankchall/repository/UserRepository.java, src/main/java/com/boolsazo/bankchall/service/UserService.java, src/main/java/com/boolsazo/bankchall/service/impl/BFRServiceImpl.java, src/main/java/com/boolsazo/bankchall/service/impl/UserServiceImpl.java
- User에 관련된 코드 일부 수정
- 설문조사 테스트 페이지 추가
- 설문조사 여부 묻는 status 추가
=> Feat: Update jpa code in UserRepository and survey test page

src/main/java/com/boolsazo/bankchall/controller/WithdrawAccountController.java, src/main/java/com/boolsazo/bankchall/domain/Account.java, src/main/java/com/boolsazo/bankchall/domain/Goal.java, src/main/java/com/boolsazo/bankchall/domain/GoalAccount.java, src/main/java/com/boolsazo/bankchall/domain/GoalAccountPK.java, src/main/java/com/boolsazo/bankchall/domain/User.java, src/main/java/com/boolsazo/bankchall/dto/AccountResponse.java, src/main/java/com/boolsazo/bankchall/dto/WithdrawRegisterRequest.java, src/main/java/com/boolsazo/bankchall/repository/AccountRepository.java, src/main/java/com/boolsazo/bankchall/repository/GoalRepository.java, src/main/java/com/boolsazo/bankchall/repository/UserRepository.java, src/main/java/com/boolsazo/bankchall/service/AccountService.java, src/main/java/com/boolsazo/bankchall/service/GoalService.java, src/main/java/com/boolsazo/bankchall/service/UserService.java, src/main/java/com/boolsazo/bankchall/service/WithdrawAccountService.java, src/main/java/com/boolsazo/bankchall/service/impl/AccountServiceImpl.java, src/main/java/com/boolsazo/bankchall/service/impl/BFRServiceImpl.java, src/main/java/com/boolsazo/bankchall/service/impl/GoalServiceImpl.java, src/main/java/com/boolsazo/bankchall/service/impl/UserServiceImpl.java, src/main/java/com/boolsazo/bankchall/service/impl/WithdrawAccountServiceImpl.java, src/test/java/com/boolsazo/bankchall/repository/AccountRepositoryTest.java
=> FIX: Long -> int로 수정

frontend/src/App.js, frontend/src/pages/Main.js, frontend/src/pages/User.js, src/main/java/com/boolsazo/bankchall/controller/HelloController.java, src/main/java/com/boolsazo/bankchall/controller/StatusController.java, src/main/java/com/boolsazo/bankchall/controller/UserController.java
=> FEAT: Show user information

README.md, frontend/src/App.js, frontend/src/index.js, frontend/src/pages/Delete.js, frontend/src/pages/Main.js, frontend/src/pages/User.js, src/main/java/com/boolsazo/bankchall/controller/HelloController.java, src/main/java/com/boolsazo/bankchall/controller/StatusController.java
alert가 두 번 뜨는 이슈가 있습니다만, 해당 이슈는 리액트를 공부하고 로직을 바꿔보도록 하겠습니다.
1. `http://localhost:8080/user`에서 **회원 탈퇴** 버튼을 누르면 `confirm 창`이 뜹니다.
2. 취소를 누르면 `http://localhost:8080/user`로 redirect 됩니다.
3. 확인을 누르면 서버 상에서 회원 탈퇴가 진행되고 `alert 창`이 띄워진 후, logout 동작이 실행됩니다.
=> FEAT: Delete user

src/main/java/com/boolsazo/bankchall/controller/GoalController.java, src/main/java/com/boolsazo/bankchall/dto/GoalListResponse.java, src/main/java/com/boolsazo/bankchall/repository/GoalRepository.java, src/main/java/com/boolsazo/bankchall/service/GoalService.java, src/main/java/com/boolsazo/bankchall/service/impl/GoalServiceImpl.java
=> Goal controller2

.gitignore
application.properties가 tracking 돼서 수정합니다
=> Fix: Update gitignore

src/main/java/com/boolsazo/bankchall/controller/StatusController.java, src/main/java/com/boolsazo/bankchall/controller/UserController.java
=> Feat: Add log at logout and delete user

frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/pages/Survey.js
- Survey page 초안입니다.
- 백엔드와 연동은 내일 진행하겠습니당.
=> Feat: Add Survey page

frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/pages/Hello.js, frontend/src/pages/Survey.js, pom.xml, src/main/java/com/boolsazo/bankchall/controller/StatusController.java, src/main/java/com/boolsazo/bankchall/controller/UserController.java
- Add exception process in StatusController
- Add exception process in UserController
=> Fix: Fix some bugs

README.md, frontend/src/pages/Delete.js, src/main/java/com/boolsazo/bankchall/controller/StatusController.java, src/main/java/com/boolsazo/bankchall/controller/UserController.java
RestController가 아닌 Controller로 옮기다 보니 `delete method`를 지원하지 않는다는 안내가 뜨기는 하나, 동작 상 문제가 없으니 우선 올립니다
=> Refactor: Move delete user from StatusController to UserController

frontend/src/pages/Survey.js, src/main/java/com/boolsazo/bankchall/controller/SurveyController.java
<h2>설문조사 제출 기능 구현</h2>
- `설문조사` 결과를 서버로 전송하여 database에 저장하는 기능 구현
<h3>주의 사항</h3>
1. 설문조사 제출 이후 `금융대사량 테스트` 페이지로 이동해야 하나, 우선 `/main`으로 이동하도록 했습니다.
2. 하지만 `/main`은 금융대사량 테스트를 완료해야 이동 가능하므로, 현재는 `/survey`로 리다이렉트 됩니다. `/user`로는 직접 이동할 수 있으니 참고 바랍니다.
3. 금융대사량 테스트를 했다고 가정하려면 mysql에서 다음과 같은 명령어를 입력 해주세요.
- 이때 `financial_type`은 null이 아니면 상관 없고, `user_id`는 본인의 user_id 값을 직접 입력해줘야 합니다.
- 설문조사 후 financial_type을 지정해주면 `/main`으로 접근 가능합니다.
```bash
update user set financial_type='MUK' where user_id=6;
```
<h3>이슈</h3>
JSON 객체의 key 값 이름이 is로 시작할 때, 제대로 전달되지 않는 이슈
- https://web2eye.tistory.com/245
=> Feat: Submit survey

src/main/java/com/boolsazo/bankchall/controller/GoalController.java, src/main/java/com/boolsazo/bankchall/service/impl/GoalServiceImpl.java
NaverSearchApi 관련 Controller, serviceImpl 수정
=> NaverSearchApi

src/main/java/com/boolsazo/bankchall/controller/UserController.java
- NaverApiInfo -> NaverLoginApi
=> Rename: Rename NaverApiInfo

frontend/src/pages/Main.js, frontend/src/pages/User.js, src/main/java/com/boolsazo/bankchall/controller/StatusController.java, src/main/java/com/boolsazo/bankchall/domain/Goal.java, src/main/java/com/boolsazo/bankchall/dto/UserResponse.java
- 목표 갯수, 목표달성률 추가
- 실테스트는 안했습니다.
=> Feat: Update user information api

README.md, frontend/src/pages/Main.js, frontend/src/pages/User.js, src/main/java/com/boolsazo/bankchall/controller/StatusController.java, src/main/java/com/boolsazo/bankchall/domain/Goal.java, src/main/java/com/boolsazo/bankchall/dto/UserResponse.java
=> Docs: Update README.md

frontend/src/pages/Survey.js
1. 직종 항목 추가
2. 로고 추가
3. 설문조사 문구 추가
=> Refactor: Update Survey.js

frontend/src/App.js, frontend/src/pages/Delete.js, frontend/src/pages/Main.js, frontend/src/pages/Survey.js, frontend/src/pages/User.js
- Add session code in test pages
- 유저 아이디를 가져오는 방법 예시: `sessionStorage.getItem("userId");`
- 세션 값이 없다면 `null` 입니다.
- 세션 값이 존재하지만, 그 값이 null인 것을 확인하려면 `"null"`과 비교해야 합니다.
- sessionStorage의 모든 value 값은 **`String`** 타입으로 관리됩니다.
=> Feat: Add Storage Session

frontend/src/components/Footers/CardsFooter.js, frontend/src/components/Footers/SimpleFooter.js, frontend/src/pages/Survey.js
- Footer and survey
필요없는 주석 지우고 내용을 조금 바꿔봤습니다,,
=> Style: Update component

frontend/src/pages/Survey.js
- 설문조사 제출 후 금융대사량 테스트를 할 수 있는 '/bfr' 링크로 리다이렉트
=> Feat: Update redirect link

frontend/src/pages/Bfr.js, frontend/src/pages/BfrTest.js, frontend/src/pages/Survey.js
=> Feat: Update survey page

frontend/src/App.js, frontend/src/components/Navbars/DemoNavbar.js, frontend/src/pages/Hello.js, frontend/src/pages/Loading.js, frontend/src/pages/Survey.js, src/main/java/com/boolsazo/bankchall/controller/HelloController.java, src/main/java/com/boolsazo/bankchall/controller/UserController.java
=> Fix: 세션-렌더링 버그

src/main/java/com/boolsazo/bankchall/controller/RuleController.java, src/main/java/com/boolsazo/bankchall/dto/RuleDetailResponse.java, src/main/java/com/boolsazo/bankchall/repository/GoalAccountRepository.java, src/main/java/com/boolsazo/bankchall/service/GoalAccountService.java, src/main/java/com/boolsazo/bankchall/service/RuleService.java, src/main/java/com/boolsazo/bankchall/service/impl/GoalAccountServiceImpl.java, src/main/java/com/boolsazo/bankchall/service/impl/RuleServiceImpl.java
=> feat: 규칙 상세보기 API 추가

frontend/src/pages/Goal.js, frontend/src/pages/GoalMain.css, frontend/src/pages/GoalMain.js, frontend/src/pages/Hello.js
=> Style: Update goalMain

frontend/src/pages/CreateGoal.js
=> Fix: Fix search

frontend/src/App.js, frontend/src/pages/BfrResult.js, frontend/src/pages/Survey.js
- Session rending error
- 단위 만 원
=> Fix: Fix somethings

frontend/src/pages/GoalFirstMain.js, frontend/src/pages/GoalMain.css, frontend/src/pages/GoalMain.js
=> Feat: Add 'add rule' button

frontend/src/pages/Bfr.js, frontend/src/pages/Hello.js, frontend/src/pages/Survey.js
=> Feat: Add session check

frontend/src/pages/BfrResult.js, frontend/src/pages/GoalMain.js
=> Fix: Session bug

frontend/src/pages/GoalMain.css, frontend/src/pages/GoalMain.js, src/main/java/com/boolsazo/bankchall/dto/GoalListResponse.java, src/main/java/com/boolsazo/bankchall/service/impl/GoalServiceImpl.java
=> Feat: Add progressbar in GoalMain

frontend/src/components/Footers/SimpleFooter.js
=> Chore: Update SimpleFooter

frontend/src/components/Footers/SimpleFooter.js, frontend/src/pages/Mypage.js
`나의 정보` 페이지에서 결혼 유무가 올바르지 않게 출력되는 것 수정
=> Fix: Fix mypage

src/main/java/com/boolsazo/bankchall/BankChallApplication.java, src/main/java/com/boolsazo/bankchall/controller/SchedulerController.java, src/main/java/com/boolsazo/bankchall/service/GoalService.java, src/main/java/com/boolsazo/bankchall/service/impl/GoalServiceImpl.java
- Init SchedulerController
- Not connect api
`24시간 기준`, `오늘 날짜에 맞는 규칙`에 대해 연결된 `출금 계좌`와 `입금 계좌`를 가져와 출력하는 스케줄러를 구현했습니다.
우선 테스트용으로 1초마다 규칙에 포함된 계좌 정보를 출력하는 코드 올립니다.
=> Feat: Add SchedulerController

README.md, frontend/package-lock.json, frontend/package.json, pom.xml
=> Version 1.0.0
